# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      env: 
        CGO_ENABLED: 0
      run: |
        go get .
        mkdir -p bin
        GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o bin/snowmachine
        GOOS=darwin go build -ldflags "-s -w" -o bin/snowmachine-darwin
        GOOS=darwin GOARCH=arm64 go build -a -ldflags "-s -w" -o bin/snowmachine-darwin-arm64
        GOOS=linux GOARCH=arm GOARM=6 go build -ldflags "-s -w" -o bin/snowmachine-armhf 
        GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o bin/snowmachine-arm64
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o bin/snowmachine.exe
   
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/snowmachine*"